"""Shanten number and effective tiles via precomputed lookup tables.

The tables (generated by scripts/generate_lookup_tables.py) give, for each suit / honor
count pattern, the minimum number of tiles to add so the pattern contains m melds
(+ optionally the pair). A hand splits into four parts (three suits + honors); combining
them is a constant-size min-plus convolution, so every query is O(1).

Bulk queries (effective tiles, discard tables) reuse the combination of the parts that
do not change, so each candidate costs one table lookup and one final combination.

Shanten counts the 16-tile form (5 melds + 1 pair). Gamesofa rules have no
seven-pairs style hands, so only the standard form is considered.
"""

from __future__ import annotations

import zlib
from functools import lru_cache
from pathlib import Path

MAX_MELDS = 5
_STRIDE = (MAX_MELDS + 1) * 2
_DATA = Path(__file__).resolve().parent / "data"
_POW5 = (1, 5, 25, 125, 625, 3125, 15625, 78125, 390625)
INF = 99

# part k covers tiles _START[k] .. _START[k] + _SIZE[k] - 1
_START = (0, 9, 18, 27)
_SIZE = (9, 9, 9, 7)
PART_OF = tuple([0] * 9 + [1] * 9 + [2] * 9 + [3] * 7)
POS_OF = tuple(list(range(9)) * 3 + list(range(7)))

Vec = tuple[list[int], list[int]]  # (cost without pair, cost with pair) for m = 0..need


@lru_cache(maxsize=1)
def _tables() -> tuple[bytes, bytes]:
    suit = zlib.decompress((_DATA / "shanten_suit.bin.z").read_bytes())
    honor = zlib.decompress((_DATA / "shanten_honor.bin.z").read_bytes())
    return suit, honor


def _part(k: int, index: int, need: int) -> Vec:
    suit, honor = _tables()
    table = honor if k == 3 else suit
    base = index * _STRIDE
    chunk = table[base: base + 2 * need + 2]
    return list(chunk[0::2]), list(chunk[1::2])


def _combine(a: Vec, b: Vec) -> Vec:
    a0, a1 = a
    b0, b1 = b
    n = len(a0)
    c0 = [INF] * n
    c1 = [INF] * n
    for i in range(n):
        x0 = a0[i]
        x1 = a1[i]
        for j in range(n - i):
            y0 = b0[j]
            v = x0 + y0
            if v < c0[i + j]:
                c0[i + j] = v
            v = x0 + b1[j]
            w = x1 + y0
            if w < v:
                v = w
            if v < c1[i + j]:
                c1[i + j] = v
    return c0, c1


def _final(a: Vec, b: Vec) -> int:
    """Cost for the full requirement (all melds + pair) from two vectors."""
    a0, a1 = a
    b0, b1 = b
    n = len(a0) - 1
    best = INF
    for i in range(n + 1):
        j = n - i
        v = a0[i] + b1[j]
        if v < best:
            best = v
        v = a1[i] + b0[j]
        if v < best:
            best = v
    return best


def _indices(hand_34: list[int]) -> list[int]:
    out = []
    for k in range(4):
        s = _START[k]
        idx = 0
        for i in range(_SIZE[k]):
            idx += hand_34[s + i] * _POW5[i]
        out.append(idx)
    return out


def _need(n_melds: int) -> int:
    need = MAX_MELDS - n_melds
    if need < 0:
        raise ValueError("n_melds must be at most 5")
    return need


def tiles_needed(hand_34: list[int], n_melds: int = 0) -> int:
    """Minimum tiles to add so the hand contains (5 - n_melds) melds and a pair."""
    need = _need(n_melds)
    idx = _indices(hand_34)
    acc = _combine(_part(0, idx[0], need), _part(1, idx[1], need))
    acc = _combine(acc, _part(2, idx[2], need))
    return _final(acc, _part(3, idx[3], need))


def shanten(hand_34: list[int], n_melds: int = 0) -> int:
    """-1 = complete, 0 = tenpai, 1 = one away, …

    hand_34: 34-length count vector of concealed tiles (melds and concealed kongs excluded).
    n_melds: number of declared sets (chi/pon/kong, including concealed kongs).
    """
    return tiles_needed(hand_34, n_melds) - 1


def is_complete(hand_34: list[int], n_melds: int = 0) -> bool:
    return shanten(hand_34, n_melds) == -1


class _Hand:
    """Part vectors of a hand with cached combinations of the unchanged parts."""

    def __init__(self, hand_34: list[int], n_melds: int) -> None:
        self.counts = hand_34
        self.need = _need(n_melds)
        self.idx = _indices(hand_34)
        self.parts = [_part(k, self.idx[k], self.need) for k in range(4)]
        self._rest1: dict[int, Vec] = {}
        self._rest2: dict[tuple[int, int], Vec] = {}

    def rest1(self, k: int) -> Vec:
        """Combination of every part except k."""
        if k not in self._rest1:
            others = [self.parts[j] for j in range(4) if j != k]
            self._rest1[k] = _combine(_combine(others[0], others[1]), others[2])
        return self._rest1[k]

    def rest2(self, j: int, k: int) -> Vec:
        key = (min(j, k), max(j, k))
        if key not in self._rest2:
            others = [self.parts[i] for i in range(4) if i not in key]
            self._rest2[key] = _combine(others[0], others[1])
        return self._rest2[key]

    def cost(self) -> int:
        return _final(self.rest1(3), self.parts[3])

    def cost_with(self, delta: dict[int, int]) -> int:
        """Cost after changing tile counts by delta (tile → ±n)."""
        changed: dict[int, int] = {}
        for t, d in delta.items():
            k = PART_OF[t]
            changed[k] = changed.get(k, self.idx[k]) + d * _POW5[POS_OF[t]]
        ks = sorted(changed)
        if len(ks) == 1:
            k = ks[0]
            return _final(self.rest1(k), _part(k, changed[k], self.need))
        if len(ks) == 2:
            j, k = ks
            acc = _combine(self.rest2(j, k), _part(j, changed[j], self.need))
            return _final(acc, _part(k, changed[k], self.need))
        vecs = [_part(k, changed.get(k, self.idx[k]), self.need) for k in range(4)]
        return _final(_combine(_combine(vecs[0], vecs[1]), vecs[2]), vecs[3])


def uke_ire(hand_34: list[int], n_melds: int = 0) -> list[int]:
    """Tiles whose draw lowers the shanten number of a 3n+1 hand.

    For a tenpai hand these are exactly the winning tiles.
    """
    h = _Hand(hand_34, n_melds)
    base = h.cost()
    return [t for t in range(34) if hand_34[t] < 4 and h.cost_with({t: 1}) < base]


def discard_table(hand_34: list[int], n_melds: int = 0) -> dict[int, tuple[int, list[int]]]:
    """For each tile in a 3n+2 hand: (shanten after discarding it, its effective tiles)."""
    h = _Hand(hand_34, n_melds)
    out: dict[int, tuple[int, list[int]]] = {}
    for d in range(34):
        if not hand_34[d]:
            continue
        after = h.cost_with({d: -1})
        uke = []
        for t in range(34):
            have = hand_34[t] - (1 if t == d else 0)
            if have >= 4:
                continue
            delta = {d: -1}
            delta[t] = delta.get(t, 0) + 1
            if h.cost_with(delta) < after:
                uke.append(t)
        out[d] = (after - 1, uke)
    return out


def shanten_after_discards(hand_34: list[int], n_melds: int = 0) -> dict[int, int]:
    """Shanten after discarding each tile of a 3n+2 hand (cheap: no effective tiles)."""
    h = _Hand(hand_34, n_melds)
    return {d: h.cost_with({d: -1}) - 1 for d in range(34) if hand_34[d]}
