"""Shanten number and effective tiles via precomputed lookup tables.

The tables (generated by scripts/generate_lookup_tables.py) give, for each suit / honor
count pattern, the minimum number of tiles to add so the pattern contains m melds
(+ optionally the pair). Combining the four parts is a constant-size min-plus convolution,
so every query is O(1).

Shanten here counts the 16-tile form (5 melds + 1 pair). Gamesofa rules have no
seven-pairs style hands, so only the standard form is considered.
"""

from __future__ import annotations

import zlib
from functools import lru_cache
from pathlib import Path

MAX_MELDS = 5
_STRIDE = (MAX_MELDS + 1) * 2
_DATA = Path(__file__).resolve().parent / "data"
_POW5 = tuple(5**i for i in range(9))
INF = 99


@lru_cache(maxsize=1)
def _tables() -> tuple[bytes, bytes]:
    suit = zlib.decompress((_DATA / "shanten_suit.bin.z").read_bytes())
    honor = zlib.decompress((_DATA / "shanten_honor.bin.z").read_bytes())
    return suit, honor


def _part(table: bytes, index: int, max_m: int) -> list[tuple[int, int]]:
    """[(cost without pair, cost with pair) for m in 0..max_m]."""
    base = index * _STRIDE
    return [(table[base + 2 * m], table[base + 2 * m + 1]) for m in range(max_m + 1)]


def _combine(a: list[tuple[int, int]], b: list[tuple[int, int]]) -> list[tuple[int, int]]:
    n = len(a)
    out: list[tuple[int, int]] = []
    for m in range(n):
        no_pair = INF
        with_pair = INF
        for k in range(m + 1):
            a0, a1 = a[k]
            b0, b1 = b[m - k]
            no_pair = min(no_pair, a0 + b0)
            with_pair = min(with_pair, a0 + b1, a1 + b0)
        out.append((no_pair, with_pair))
    return out


def tiles_needed(hand_34: list[int], n_melds: int = 0) -> int:
    """Minimum tiles to add so the hand contains (5 - n_melds) melds and a pair."""
    need = MAX_MELDS - n_melds
    if need < 0:
        raise ValueError("n_melds must be at most 5")
    suit, honor = _tables()
    acc: list[tuple[int, int]] | None = None
    for s in range(3):
        idx = 0
        for i in range(9):
            idx += hand_34[9 * s + i] * _POW5[i]
        part = _part(suit, idx, need)
        acc = part if acc is None else _combine(acc, part)
    idx = 0
    for i in range(7):
        idx += hand_34[27 + i] * _POW5[i]
    assert acc is not None
    acc = _combine(acc, _part(honor, idx, need))
    return acc[need][1]


def shanten(hand_34: list[int], n_melds: int = 0) -> int:
    """-1 = complete, 0 = tenpai, 1 = one away, …

    hand_34: 34-length count vector of concealed tiles (melds and concealed kongs excluded).
    n_melds: number of declared sets (chi/pon/kong, including concealed kongs).
    """
    return tiles_needed(hand_34, n_melds) - 1


def is_complete(hand_34: list[int], n_melds: int = 0) -> bool:
    return shanten(hand_34, n_melds) == -1


def uke_ire(hand_34: list[int], n_melds: int = 0) -> list[int]:
    """Tiles whose draw lowers the shanten number of a 3n+1 hand.

    For a tenpai hand these are exactly the winning tiles.
    """
    base = shanten(hand_34, n_melds)
    counts = list(hand_34)
    out: list[int] = []
    for t in range(34):
        if counts[t] >= 4:
            continue
        counts[t] += 1
        if shanten(counts, n_melds) < base:
            out.append(t)
        counts[t] -= 1
    return out
